services:

  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./seederData/seed.sql:/docker-entrypoint-init/1stinit.sql
      - $HOME/database:/var/lib/mysql
    ports:
    - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: example
